
-- drop table wc_albums purge;

create table wc_albums (
    id            number            generated by default on null as identity (start with 1) primary key not null
  , id_user	      number not null     
  , name 		  varchar2(50)   not null
  , code          varchar2(50)
  , description   varchar2(1000)  
  , active_ind    varchar2(2)
  
  , created_by   varchar2(60)       default
                   coalesce(
                       sys_context('APEX$SESSION','app_user')
                     , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     , sys_context('userenv','session_user')
                   )
                   not null
  , created_on   date               default sysdate not null
  , updated_by   varchar2(60)
  , updated_on   date
  --, constraint wc_albums_u unique (id)
  , constraint wc_albums_fk foreign key (id_user)
	references wc_users (id) 
)
enable primary key using index
/

comment on table wc_albums is 'Figures for swap';

comment on column wc_albums.id is 'Unique Id'; 

comment on column wc_albums.created_on is 'Date the record was first created';
comment on column wc_albums.updated_by is 'User that last modified this record';
comment on column wc_albums.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wc_albums_u_trg
--------------------------------------------------------
create or replace trigger wc_albums_u_trg
before update
on wc_albums
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
