
-- drop table wc_figures purge;

create table wc_figures (
    id            number            generated by default on null as identity (start with 1) primary key not null
  , album_id      number    
  , figure_number number   not null
  , status_code   varchar2(50)
  , description   varchar2(1000)
  , football_player  varchar2(500)
  , type_code    varchar2(50) 
  , completed_ind  varchar2(2) not null
  , duplicated_ind  varchar2(2) not null   
  , created_by   varchar2(60)       default
                   coalesce(
                       sys_context('APEX$SESSION','app_user')
                     , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     , sys_context('userenv','session_user')
                   )
                   not null
  , created_on   date               default sysdate not null
  , updated_by   varchar2(60)
  , updated_on   date
  --, constraint wc_figures_u unique (id)
  , constraint wc_figures_u UNIQUE (album_id,figure_number)
  , constraint wc_figures_fk1 foreign key (album_id)
	references wc_albums (id)  
)
enable primary key using index
/

comment on table wc_figures is 'Figures for swap';

comment on column wc_figures.id is 'Unique Id';
comment on column wc_figures.album_id is 'The name of the album_id';
comment on column wc_figures.Figure_Number is 'Number of figure';
comment on column wc_figures.Status_Code is 'Status, can be : "BUSCANDO","REPETIDO","COMPLETADO","DEFAULT"';
comment on column wc_figures.Description is 'Any description';
comment on column wc_figures.Football_Player is 'Name od the futoball player';
comment on column wc_figures.Type_Code is 'Type of figure, can be cromo,stadium,normal,specials';

comment on column wc_figures.created_on is 'Date the record was first created';
comment on column wc_figures.updated_by is 'User that last modified this record';
comment on column wc_figures.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wc_figures_u_trg
--------------------------------------------------------
create or replace trigger wc_figures_u_trg
before update
on wc_figures
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
