
-- drop table wc_group_users purge;

create table wc_group_users (
    id            	number	generated by default on null as identity (start with 1) primary key not null
  , id_group    	number   not null 
  , id_user 		number   not null 
  , contact_info     varchar2(1000) 
  , created_by   varchar2(60)       default
                   coalesce(
                       sys_context('APEX$SESSION','app_user')
                     , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     , sys_context('userenv','session_user')
                   )
                   not null
  , created_on   date               default sysdate not null
  , updated_by   varchar2(60)
  , updated_on   date
  --, constraint wc_group_users_u unique (id)
  , constraint wc_group_users_fk1 foreign key (id_group)
	references wc_groups (id) 
  , constraint wc_group_users_fk2 foreign key (id_user)
	references wc_users (id) 
)
enable primary key using index
/

comment on table wc_group_users is 'group_users for swap';

comment on column wc_group_users.created_by is 'User that created this record';
comment on column wc_group_users.created_on is 'Date the record was first created';
comment on column wc_group_users.updated_by is 'User that last modified this record';
comment on column wc_group_users.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wc_group_users_u_trg
--------------------------------------------------------
create or replace trigger wc_group_users_u_trg
before update
on wc_group_users
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
