
-- drop table wc_groups purge;

create table wc_groups (
    id            number            generated by default on null as identity (start with 1) primary key not null
  , name    	    varchar2(500)   not null
  , group_code      varchar2(50)
  , description     varchar2(1000)  not null
  , number_members  number
  , group_image		blob
  , private_ind       varchar2(1)   not null
  , eliminated_ind    varchar2(1)   not null
  , created_by   varchar2(60)       default
                   coalesce(
                       sys_context('APEX$SESSION','app_user')
                     , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     , sys_context('userenv','session_user')
                   )
                   not null
  , created_on   date               default sysdate not null
  , updated_by   varchar2(60)
  , updated_on   date
  --, constraint wc_groups_u unique (id)
)
enable primary key using index
/

comment on table wc_groups is 'groups for swap';

 
comment on column wc_groups.created_by is 'User that created this record';
comment on column wc_groups.created_on is 'Date the record was first created';
comment on column wc_groups.updated_by is 'User that last modified this record';
comment on column wc_groups.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wc_groups_u_trg
--------------------------------------------------------
create or replace trigger wc_groups_u_trg
before update
on wc_groups
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
