
-- drop table wc_user_mails purge;

create table wc_user_mails (
    id            number generated by default on null as identity (start with 1) primary key not null
  , id_user	      number not null   	
  , user_send  			varchar2(50)   
  , user_get  			varchar2(50)
  , message   			varchar2(4000) not null
  , ask_trade  			varchar2(1)	
  , read_ind  			varchar2(1) not null 
  , eliminated_ind		varchar2(1)	not null   
  , created_by   varchar2(60)       default
                   coalesce(
                       sys_context('APEX$SESSION','app_user')
                     , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     , sys_context('userenv','session_user')
                   )
                   not null
  , created_on   date               default sysdate not null
  , updated_by   varchar2(60)
  , updated_on   date
  --, constraint wc_user_mails_u unique (id)
  , constraint wc_user_mails_fk foreign key (id_user)
	references wc_users (id) 
)
enable primary key using index
/

comment on table wc_user_mails is 'user_mails for swap';

comment on column wc_user_mails.created_by is 'User that created this record'; 
comment on column wc_user_mails.created_on is 'Date the record was first created';
comment on column wc_user_mails.updated_by is 'User that last modified this record';
comment on column wc_user_mails.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wc_user_mails_u_trg
--------------------------------------------------------
create or replace trigger wc_user_mails_u_trg
before update
on wc_user_mails
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
